# Generated by Django 2.1 on 2019-08-13 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 14, 20, 45, 415495)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 20, 45, 420496)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 14, 20, 45, 413495)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechasalida',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 14, 20, 45, 413495)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 20, 45, 419496)),
        ),
    ]
