# Generated by Django 2.1 on 2019-08-14 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0002_auto_20190813_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='CliProentidad',
            new_name='cliProentidad',
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 19, 59, 51, 183544)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 19, 59, 51, 188544)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 19, 59, 51, 180542)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechasalida',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 19, 59, 51, 186545)),
        ),
    ]
