# Generated by Django 2.1 on 2019-08-26 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0004_auto_20190818_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['nombre'], 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterModelOptions(
            name='cliproentidad',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente o Proveedor', 'verbose_name_plural': 'Cliente o Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='comprainventario',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalle de Compra'},
        ),
        migrations.AlterModelOptions(
            name='detfactura',
            options={'ordering': ['id'], 'verbose_name': 'Detalle factura', 'verbose_name_plural': 'Detalle factura'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['id'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Factura'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['material'], 'verbose_name': 'Inventario General', 'verbose_name_plural': 'Inventario General'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido de Clientes Articulo', 'verbose_name_plural': 'Pedido de Clientes articulos'},
        ),
        migrations.AlterModelOptions(
            name='pedidodetalle',
            options={'ordering': ['id'], 'verbose_name': 'Materiales que se usaran en el Pedido', 'verbose_name_plural': 'Materiales que se usaran en el Pedido'},
        ),
        migrations.AlterModelOptions(
            name='tipomaterial',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo Material', 'verbose_name_plural': 'Tipo Materiales'},
        ),
        migrations.RemoveField(
            model_name='comprainventario',
            name='Inventario',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='inventario',
        ),
        migrations.AddField(
            model_name='comprainventario',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.Material'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipoinventario',
            field=models.IntegerField(choices=[(1, 'Compra'), (2, 'Ingreso'), (3, 'Modificado'), (4, 'Produccion')], default=2),
        ),
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliProentidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.CliProentidad'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='material',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.Material'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 25, 19, 57, 58, 905195)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 19, 57, 58, 919195)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 25, 19, 57, 58, 898192)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 19, 57, 58, 913193)),
        ),
    ]
