# Generated by Django 2.1 on 2019-09-12 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0005_auto_20190825_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['fecentrega'], 'verbose_name': 'Pedido de Clientes Articulo', 'verbose_name_plural': 'Pedido de Clientes articulos'},
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='pedido',
        ),
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(default='', upload_to='Articulo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliproentidad',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comprainventario',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='detfactura',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='cantidad'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipomaterial',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 20, 42, 51, 153637)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 20, 42, 51, 162638)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 11, 20, 42, 51, 150636)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 20, 42, 51, 157637)),
        ),
    ]
