# Generated by Django 2.1 on 2019-09-19 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0007_auto_20190911_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 16, 47, 5, 870803)),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='comprainventario',
            name='valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 16, 47, 5, 881805)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 19, 16, 47, 5, 868804)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='material',
            name='arprecio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='coutainicial',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=19, verbose_name='coutainicial'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 16, 47, 5, 874803)),
        ),
    ]
