# Generated by Django 2.1 on 2019-09-27 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0008_auto_20190919_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliproentidad',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 27, 10, 7, 58, 482422)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 7, 58, 514426)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 27, 10, 7, 58, 478421)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 10, 7, 58, 495424)),
        ),
    ]
