# Generated by Django 2.1 on 2019-10-26 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0011_auto_20190930_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidoarticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('abono', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scmi.Articulo')),
            ],
            options={
                'verbose_name_plural': 'Pedido de detalle articulos',
                'ordering': ['articulo'],
                'verbose_name': 'Pedido de detalle Articulo',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='detalleproforma',
            name='maximo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='image',
            field=models.ImageField(default='', upload_to='empresa/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='descripcion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='proforma',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proforma',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 14, 16, 50, 17968)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 16, 50, 31970)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 14, 16, 50, 9968)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 16, 50, 24969)),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fec',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 16, 50, 33971)),
        ),
    ]
