# Generated by Django 2.1 on 2019-10-26 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0013_auto_20191026_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoarticulo',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.Pedido'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 14, 38, 28, 157597)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 38, 28, 166596)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 14, 38, 28, 153593)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='articulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.Articulo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 38, 28, 162596)),
        ),
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='articulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='scmi.Articulo'),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fec',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 38, 28, 167596)),
        ),
    ]
