# Generated by Django 2.1 on 2019-10-26 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0019_auto_20191026_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 15, 22, 18, 68995)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 22, 18, 78996)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 15, 22, 18, 62994)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 22, 18, 73996)),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fec',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 22, 18, 80997)),
        ),
    ]
