# Generated by Django 2.1 on 2019-10-26 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmi', '0021_auto_20191026_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 15, 50, 55, 585809)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecventa',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 50, 55, 602812)),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fechaingreso',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 15, 50, 55, 581809)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecentrega',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 50, 55, 590810)),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='fec',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 15, 50, 55, 604812)),
        ),
    ]
